# google_cloud:
#   service_account_path: "${GOOGLE_APPLICATION_CREDENTIALS}"
#   service_account_creds: "${GCP_CREDS}"
#   project: "project-name"
#   location: "location-name"

slack:
  bot_token: "${SLACK_BOT_TOKEN}"
  debug_channel: "${DEBUG_CHANNEL}"
  debug_user: "${DEBUG_USER}"
